spring:
  mail:
    host: smtp.gmail.com
    username: xxx@gmail.com
    port: '587'
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            required: 'true'
            enable: 'true'
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  h2:
    console:
      settings:
        trace: 'false'
        web-allow-others: 'false'
      enabled: 'true'
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: '5'
    job-store-type: jdbc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
